package requests

type Item struct {
	InvoiceDocument                int      `json:"InvoiceDocument"`
	InvoiceDocumentItem            int      `json:"InvoiceDocumentItem"`
	DocumentItemCategory           *string  `json:"DocumentItemCategory"`
	InvoiceDocumentItemText        *string  `json:"InvoiceDocumentItemText"`
	CreationDate                   *string  `json:"CreationDate"`
	CreationTime                   *string  `json:"CreationTime"`
	ItemBillingIsConfirmed         *bool    `json:"ItemBillingIsConfirmed"`
	ItemBillingConfStatus          *string  `json:"ItemBillingConfStatus"`
	Buyer                          *int     `json:"Buyer"`
	Seller                         *int     `json:"Seller"`
	DeliverToParty                 *int     `json:"DeliverToParty"`
	DeliverFromParty               *int     `json:"DeliverFromParty"`
	ProductStandardID              *string  `json:"ProductStandardID"`
	Batch                          *string  `json:"Batch"`
	Product                        *string  `json:"Product"`
	ProductGroup                   *string  `json:"ProductGroup"`
	ProductionPlantPartnerFunction *string  `json:"ProductionPlantPartnerFunction"`
	ProductionPlantBusinessPartner *string  `json:"ProductionPlantBusinessPartner"`
	ProductionPlant                *string  `json:"ProductionPlant"`
	ProductionPlantStorageLocation *string  `json:"ProductionPlantStorageLocation"`
	IssuingPlantPartnerFunction    *string  `json:"IssuingPlantPartnerFunction"`
	IssuingPlantBusinessPartner    *string  `json:"IssuingPlantBusinessPartner"`
	IssuingPlant                   *string  `json:"IssuingPlant"`
	IssuingPlantStorageLocation    *string  `json:"IssuingPlantStorageLocation"`
	ReceivingPlantPartnerFunction  *string  `json:"ReceivingPlantPartnerFunction"`
	ReceivingPlantBusinessPartner  *string  `json:"ReceivingPlantBusinessPartner"`
	ReceivingPlant                 *string  `json:"ReceivingPlant"`
	ReceivingPlantStorageLocation  *string  `json:"ReceivingPlantStorageLocation"`
	ServicesRenderedDate           *string  `json:"ServicesRenderedDate"`
	InvoiceQuantity                *float32 `json:"InvoiceQuantity"`
	InvoiceQuantityUnit            *string  `json:"InvoiceQuantityUnit"`
	InvoiceQuantityInBaseUnit      *float32 `json:"InvoiceQuantityInBaseUnit"`
	BaseUnit                       *string  `json:"BaseUnit"`
	ActualGoodsIssueDate           *string  `json:"ActualGoodsIssueDate"`
	ActualGoodsIssueTime           *string  `json:"ActualGoodsIssueTime"`
	ActualGoodsReceiptDate         *string  `json:"ActualGoodsReceiptDate"`
	ActualGoodsReceiptTime         *string  `json:"ActualGoodsReceiptTime"`
	ItemGrossWeight                *float32 `json:"ItemGrossWeight"`
	ItemNetWeight                  *float32 `json:"ItemNetWeight"`
	ItemWeightUnit                 *string  `json:"ItemWeightUnit"`
	NetAmount                      *float32 `json:"NetAmount"`
	TaxAmount                      *float32 `json:"TaxAmount"`
	GrossAmount                    *float32 `json:"GrossAmount"`
	GoodsIssueOrReceiptSlipNumber  *string  `json:"GoodsIssueOrReceiptSlipNumber"`
	TransactionCurrency            *string  `json:"TransactionCurrency"`
	PricingDate                    *string  `json:"PricingDate"`
	ProductTaxClassification       *string  `json:"ProductTaxClassification"`
	Project                        *string  `json:"Project"`
	OrderID                        *int     `json:"OrderID"`
	OrderItem                      *int     `json:"OrderItem"`
	OrderType                      *string  `json:"OrderType"`
	ContractType                   *string  `json:"ContractType"`
	OrderVaridityStartDate         *string  `json:"OrderVaridityStartDate"`
	OrderVaridityEndDate           *string  `json:"OrderVaridityEndDate"`
	InvoiceScheduleStartDate       *string  `json:"InvoiceScheduleStartDate"`
	InvoiceScheduleEndDate         *string  `json:"InvoiceScheduleEndDate"`
	DeliveryDocument               *int     `json:"DeliveryDocument"`
	DeliveryDocumentItem           *int     `json:"DeliveryDocumentItem"`
	OriginDocument                 *int     `json:"OriginDocument"`
	OriginDocumentItem             *int     `json:"OriginDocumentItem"`
	ReferenceDocument              *int     `json:"ReferenceDocument"`
	ReferenceDocumentItem          *int     `json:"ReferenceDocumentItem"`
	ReferenceDocumentType          *string  `json:"ReferenceDocumentType"`
	ExternalReferenceDocument      *string  `json:"ExternalReferenceDocument"`
	ExternalReferenceDocumentItem  *string  `json:"ExternalReferenceDocumentItem"`
	TaxCode                        *string  `json:"TaxCode"`
	TaxRate                        *float32 `json:"TaxRate"`
	CountryOfOrigin                *string  `json:"CountryOfOrigin"`
}
